### ISSUE TITLE
Button is to big on astra theme 

### ISSUE THREAD

**Issue by ofer777** [nielslange/smntcs-woocommerce-quantity-buttons#4]
<img width="508" alt="Screenshot 2019-08-21 at 20 36 51" src="https://user-images.githubusercontent.com/46934496/63454450-825d6800-c453-11e9-8460-2f844a498531.png">
can you please help how to resize the button?

**Comment by nielslange** [comment]
@ofer777 Can you post the URL of your site, so that I can take a look at it? I might have to overwrite some theme related CSS of the Astra theme.

**Comment by ofer777** [comment]
Thanks for the quick reply!

URL: http://speedybox.co.uk

Regards,

Ofer Hai

**Comment by ofer777** [comment]
Also I try before on “hello” theme and was the some problems of sizes.

Best Regards,

Ofer Hai

**Comment by nielslange** [comment]
Hello @ofer777,

Please add the following CSS to your site:

```css
.woocommerce .quantity input[type=button],
.woocommerce .quantity input[type=number],
.woocommerce div.product form.cart .button.single_add_to_cart_button {
  height: 40px;
  padding: 5px 40px;
  vertical-align: middle;
}
```

This should solve the styling issue. 

My plugin doesn't add any stylings to the buttons though, thus, the styling issues are caused both by the Astra and Hello themes and it's quite common that themes overwrite the default WooCommerce styling which leads to these side effects.
